version: '3'

services:
  traefik:
    image: traefik:v3.1.6
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=kozak@talko.cz"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.kozak.in`)"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.kozak.in`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.routers.api.middlewares=myauth"
      - "traefik.http.middlewares.myauth.basicauth.users=tomas:$$2y$$05$$N/VKTiO5sJTfxn1xybZ8gelqg7d4fdUb4tW67WVsgCmiqsNeUP.W."
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traef

  # kozak.in
  kozak_in_php:
    image: registry.gitlab.com/kozaktomas/personal-web:latest
    volumes:
      - ./data/kozak-in/sock:/sock
    environment:
      DISCORD_WEBHOOK_URL: "${KOZAK_IN_DISCORD_WEBHOOK_URL}"
    networks:
      - traef
  kozak_in_lb:
    image: ghcr.io/kozaktomas/gophpfpm:main
    labels:
      - "traefik.http.routers.kozak-in.entrypoints=websecure"
      - "traefik.http.routers.kozak-in.rule=Host(`kozak.in`)"
      - "traefik.http.routers.kozak-in.tls=true"
      - "traefik.http.routers.kozak-in.tls.certresolver=le"
      - "traefik.http.routers.kozak-in-redirect.entrypoints=web"
      - "traefik.http.routers.kozak-in-redirect.rule=Host(`kozak.in`)"
      - "traefik.http.routers.kozak-in-redirect.tls=false"
      - "traefik.http.routers.kozak-in-redirect.middlewares=redirect-to-https"
    volumes:
      - ./data/kozak-in/sock:/sock
    ports:
      - "8091:8080"
    command:
      - "--app=personal_web"
      - "--port=8080"
      - "--socket=/sock/php-fpm.sock"
      - "--index-file=/var/www/html/app/index.php"
      - "--access-log"
      - "--fpm-pool-size=16"
    depends_on:
      - kozak_in_php
    networks:
      - traef
  kozak_in_php_exporter:
    image: hipages/php-fpm_exporter
    depends_on:
      - kozak_in_php
    volumes:
      - ./data/kozak-in/sock:/sock
    ports:
      - "9253:9253"
    command:
      - "--phpfpm.scrape-uri"
      - "unix:///sock/php-fpm.sock;/fpm-status"
    networks:
      - traef
  static_kozak_in:
    image: nginx
    labels:
      - "traefik.http.routers.static-kozak-in.entrypoints=websecure"
      - "traefik.http.routers.static-kozak-in.rule=Host(`static.kozak.in`)"
      - "traefik.http.routers.static-kozak-in.tls=true"
      - "traefik.http.routers.static-kozak-in.tls.certresolver=le"
      - "traefik.http.routers.static-kozak-in-redirect.entrypoints=web"
      - "traefik.http.routers.static-kozak-in-redirect.rule=Host(`static.kozak.in`)"
      - "traefik.http.routers.static-kozak-in-redirect.tls=false"
      - "traefik.http.routers.static-kozak-in-redirect.middlewares=redirect-to-https"
    volumes:
      - ./nginx/static.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/html
    ports:
      - "8082:80"
    networks:
      - traef

  # svazzen.cz
  svazzen_cz:
    image: nginx
    labels:
      - "traefik.http.routers.svazzen-cz.entrypoints=websecure"
      - "traefik.http.routers.svazzen-cz.rule=Host(`svazzen.cz`)"
      - "traefik.http.routers.svazzen-cz.tls=true"
      - "traefik.http.routers.svazzen-cz.tls.certresolver=le"
      - "traefik.http.routers.svazzen-cz-redirect.entrypoints=web"
      - "traefik.http.routers.svazzen-cz-redirect.rule=Host(`svazzen.cz`)"
      - "traefik.http.routers.svazzen-cz-redirect.tls=false"
      - "traefik.http.routers.svazzen-cz-redirect.middlewares=redirect-to-https"
    volumes:
      - ./nginx/svazzen.conf:/etc/nginx/conf.d/default.conf
      - ./svazzen:/var/www/html
    ports:
      - "8083:80"
    networks:
      - traef

  # 7 - pub app
  redis:
    image: redis:latest
    volumes:
      - ./redis_data:/data
    networks:
      - traef

networks:
  traef:
    external: true
