#!/bin/bash

# load secrets from 1password
# shellcheck disable=SC2046
eval $(op item get dev/tf/infra --format json | jq -r '.fields[0].value')

terraform init \
    -backend-config="username=${TF_VAR_BACKEND_USERNAME}" \
    -backend-config="password=${TF_VAR_BACKEND_TOKEN}" \
